[package]
name = "ross"
version = "0.1.1"
authors = ["Lee Katz <gzu2@cdc.gov>"]

[[bin]]
name = "friends_carol"
path = "src/bin/friends_carol.rs"

[[bin]]
name = "friends_rachel"
path = "src/bin/friends_rachel.rs"

[[bin]]
name = "friends_monica"
path = "src/bin/friends_monica.rs"

[[bin]]
name = "friends_joey"
path = "src/bin/friends_joey.rs"

[[bin]]
name = "friends_phoebe"
path = "src/bin/friends_phoebe.rs"

[[bin]]
name = "friends_ursula"
path = "src/bin/friends_ursula.rs"

[[bin]]
name = "friends_gunther"
path = "src/bin/friends_gunther.rs"

[dependencies]
bio = "0.15"
regex = "0.2"
getopts = "0.2"
statistical = "0.1.1"
multiqueue = "0.3.2"
rand = "0.4"
